### ISSUE TITLE
npm install failed with node-sass error

### ISSUE THREAD

**Issue by MasterPi-2124** [BabyBlockchains/Lotus#7]
When installing ```vue``` from ```npm install```, it returns an error:
> ```
> error /home/masterpi/.node-gyp/16.1.0/include/node/v8-internal.h:452:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
> ```
It means that ```node-sass``` doesn't recognize ```remove_cv_t```, which is in Nodejs 16, so a downgrade to Nodejs 14 or 15 is recommended.

**Comment by faddat** [comment]
yup, use nodejs 14 :cry:
